###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, List, Optional, Union, Literal

from . import types

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################


class Activity(BaseModel):
    
    
    fileId: Optional[Union[Optional[int], Optional[str]]] = None
    fileName: Optional[str] = None
    duration: Optional[Union[Optional[str], Optional[int], Optional[float]]] = None
    distance: Optional[Union[Optional[float], Optional[str]]] = None
    activityType: Optional[str] = None
    calories: Optional[Union[Optional[int], Optional[str]]] = None
    ascent: Optional[Union[Optional[int], Optional[str]]] = None
    avgPace: Optional[str] = None
    minHeartRate: Optional[Union[Optional[int], Optional[str]]] = None
    maxHeartRate: Optional[Union[Optional[int], Optional[str]]] = None
    avgHeartRate: Optional[Union[Optional[int], Optional[str]]] = None
    timeFinished: Optional[str] = None

class Training(BaseModel):
    
    
    day: Optional[str] = None
    activity: Optional[str] = None
    targetPace: Optional[float] = None
    length: Optional[float] = None

class TrainingPlan(BaseModel):
    
    
    training: List["Week"]

class Week(BaseModel):
    
    
    week: Optional[int] = None
    training: List["Training"]
