###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, List, Optional, Union, Literal


class Activity(BaseModel):
    
    
    fileId: Union[int, str]
    fileName: str
    duration: Union[str, int, float]
    distance: Union[float, str]
    activityType: str
    calories: Union[int, str]
    ascent: Union[int, str]
    avgPace: str
    minHeartRate: Union[int, str]
    maxHeartRate: Union[int, str]
    avgHeartRate: Union[int, str]
    timeFinished: str

class Training(BaseModel):
    
    
    day: str
    activity: str
    targetPace: float
    length: float

class TrainingPlan(BaseModel):
    
    
    training: List["Week"]

class Week(BaseModel):
    
    
    week: int
    training: List["Training"]
